// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsR04GFev5VdtgCHdjJQCxVhJz-Z-2cx0',
    appId: '1:638660365355:web:5192295333726156a1ee6e',
    messagingSenderId: '638660365355',
    projectId: 'flutter-2c2f0',
    authDomain: 'flutter-2c2f0.firebaseapp.com',
    storageBucket: 'flutter-2c2f0.appspot.com',
    measurementId: 'G-HMPL025E13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApvXY5OvFcYvK_jIQ2jbXzltJA1ebG1YM',
    appId: '1:638660365355:android:a672d52927312775a1ee6e',
    messagingSenderId: '638660365355',
    projectId: 'flutter-2c2f0',
    storageBucket: 'flutter-2c2f0.appspot.com',
  );
}
